config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  
  resources :expenses do
    member do
      post 'approve'
      post 'deny'
      get 'user_name'
    end
  end
  
  devise_for :employees, path: 'employees'
  devise_for :managers, path: 'managers'
  
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  helper ExpensesHelper
  load_and_authorize_resource
  before_action :set_expense, only: [:show, :edit, :update, :approve, :deny, :user_name]

  # GET /expenses
  # GET /expenses.json
  def index
    if current_manager != nil
      @expenses = Expense.all
    elsif current_employee != nil
      @expenses = Expense.where(user_id: current_employee.id)
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.user_id = current_employee.id
    @expense.status = 'Pendente'
    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    @expense = Expense.find(params[:id])
    @expense.update_attributes({:status => 'Aprovada'})
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully approved.' }
      format.json { head :no_content }
    end
  end

  def deny
    @expense = Expense.find(params[:id])
    @expense.update_attributes({:status => 'Rejeitada'})
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully Denied.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:description, :date, :value, :picture)
    end

  
end

app/helpers/expenses_helper.rb
module ExpensesHelper
    def get_user_name(user_id)
        user_id.blank? ? '' : Employee.find(params[:id], user_id).name
    end
    def format_date(data_expense)
        data_expense.blank? ? '' : data_expense.strftime("%d/%m/%Y")
    end
    def format_number_real(value)
        number_to_currency(value, unit: "R$", separator: ",", delimiter: "")
    end
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true, :html => { :multipart => true }) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label class="label">Descrição</label>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <label class="label">Data</label>
    <%= form.text_field :date, class: "datepicker" %>
  </div>

   <script>
    document.addEventListener('DOMContentLoaded', function () {
        var options = {
            defaultDate: new Date(),
            setDefaultDate: true
        };
        var elems = document.querySelector('.datepicker');
        var instance = M.Datepicker.init(elems, options);
        // instance.open();
        instance.setDate(new Date());
    });
  </script>
  <div class="field">
    <label class="label">Valor</label>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <label class="label">Comprovante</label>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit "Criar despesa"%>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editar Despesa</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Mostrar', @expense %> |
<%= link_to 'Voltar', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>
    <h1>Despesas</h1>

    <table>
      <thead>
        <tr>
          <th>Descrição</th>
          <th>Data</th>
          <th>Valor</th>
          <th>Situação</th>
          <% if can? :approve, Expense %>
            <th>Requisitante</th>
          <% end %>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @expenses.each do |expense| %>
          <tr>
            <td><%= expense.description %></td>
            <td><%= format_date(expense.date) %></td>
            <td><%= format_number_real(expense.value) %></td>
            <td><%= expense.status %></td>
            <% if can? :approve, Expense %>
              <td><%= get_user_name(expense.user_id) %></td>
            <% end %>
            <td>
              <% if can? :approve, Expense %>
                <%= link_to 'Aprovar', approve_expense_path(expense), method: :post %>
              <% end %>
            </td>
            <td>
              <% if can? :deny, Expense %>
                <%= link_to 'Negar', deny_expense_path(expense), method: :post %>
              <% end %>
            </td> 
            <td><%= link_to 'Mostrar', expense %></td>
            <td>
              <% if can? :edit, Expense %>
                <% if can? :edit, expense %>
                  <%= link_to 'Editar', edit_expense_path(expense) %>
                <% end %>  
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  
  <!-- Modal Trigger -->
  <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>

    <br>
    <% if can? :create, Expense %>
      <div class="fixed-action-btn">
        <a href="/expenses/new", class="btn-floating btn-large light-blue darken-1">
          <i class="large material-icons">add_circle</i>
        </a>
      </div>
    <% end %>

app/views/expenses/new.html.erb
<h1>Nova despesa</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Voltar', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Data:</strong>
  <%= format_date(@expense.date) %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @expense.value %>
</p>

<p>
  <strong>Status:</strong>
  <%= @expense.status %>
</p>

<p>
  <strong>Comprovante:</strong>
  <%= image_tag(@expense.picture_url, :width => 600) if @expense.picture.present? %>
</p>


<%= link_to 'Editar', edit_expense_path(@expense) %> |
<%= link_to 'Voltar', expenses_path %>