config/routes.rb
Rails.application.routes.draw do
  root 'page#index'
  
  resources :expenses do
    member do
      post 'approve'
      post 'deny'
      get 'user_name'
    end
  end
  
  devise_for :employees, path: 'employees'
  devise_for :managers, path: 'managers'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Espressito</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    
    <nav class="light-blue lighten-1" role="navigation">
      <div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo"><%= image_tag 'logo.svg' %></a>
        <ul class="right hide-on-med-and-down">
          <% if manager_signed_in? %>
                <li><a><%= current_manager.name %></a></li>
                <li><%= link_to "Sair", destroy_manager_session_path, method: :delete, class: "nav-link" %></li>
              <% else %>
                <% if employee_signed_in? %>
                  <li><a><%= current_employee.name %></a></li>
                  <li><%= link_to "Sair", destroy_employee_session_path, method: :delete, class: "nav-link" %></li>
                <% end %>
              <% end %>
        </ul>
      </div>
    </nav>

    <body>
      <h5 class="center-align">
        <div class="container center-align"> 
          <%= yield %>
        <div>
      </h5>
    </body>
  </head>
</html>